<?php

if (!defined('XOOPS_ROOT_PATH')) {
    exit;
}
    $mydirname = basename(__DIR__);

$modversion['name'] = _MI_ADS_NAME;
$modversion['version'] = '3.0beta3F';
$modversion['description'] = _MI_ADS_DESC;
$modversion['credits'] = "Pascal Le Boustouller / redesigned by glassJAw and jojup from myxoops.de team /redesigned by Tom<br><a href='http://malaika.s31.xrea.com/'>Malaika System</a> then redesigned by John Mordo user jlm69 at Xoops<br><a href='http://www.jlmzone.com/'>jlmzone.com</a>";
$modversion['author'] = "John Mordo jlm69 at Xoops<br><a href='http://www.jlmzone.com/'>jlmzone.com</a>";
$modversion['license'] = 'GPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/ads.gif';
$modversion['dirname'] = (string)$mydirname;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Templates
$modversion['templates'][1]['file'] = 'ads_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'ads_adlist.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'ads_category.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'ads_item.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'ads_view_myads.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'ads_rate_item.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'ads_rate_user.html';
$modversion['templates'][7]['description'] = '';

// Blocks
$modversion['blocks'][1]['file'] = 'ads.php';
$modversion['blocks'][1]['name'] = _MI_ADS_BNAME;
$modversion['blocks'][1]['description'] = 'Shows new listings';
$modversion['blocks'][1]['show_func'] = 'ads_show';
$modversion['blocks'][1]['template'] = 'ads_block_new.html';

// Menu
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'ads_categories';
$modversion['tables'][1] = 'ads_ip_log';
$modversion['tables'][2] = 'ads_listing';
$modversion['tables'][3] = 'ads_type';
$modversion['tables'][4] = 'ads_price';
$modversion['tables'][5] = 'ads_item_votedata';
$modversion['tables'][6] = 'ads_user_votedata';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'ads_search';

// Comments
$modversion['hasComments'] = 1;

$modversion['comments']['itemName'] = 'usid';
$modversion['comments']['pageName'] = 'index.php?pa=viewmyads&usid=$usid';
$modversion['comments']['extraParams'] = ['cid'];
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'ads_com_approve';
$modversion['comments']['callback']['update'] = 'ads_com_update';

// Config Settings
$modversion['hasconfig'] = 1;

// $xoopsModuleConfig['monnaie']
$modversion['config'][1] = [
'name' => 'ads_monnaie' ,
'title' => '_MI_ADS_MONEY' ,
'description' => '',
'formtype' => 'textbox' ,
'valuetype' => 'text' ,
'default' => '$' ,
'options' => [],
];

 //$xoopsModuleConfig['koivi']
$modversion['config'][] = [
'name' => 'ads_koivi' ,
'title' => '_MI_ADS_KOIVI' ,
'description' => '',
'formtype' => 'yesno' ,
'valuetype' => 'int' ,
'default' => '0' ,
'options' => [],
];

 //$xoopsModuleConfig['moderated']
$modversion['config'][] = [
'name' => 'ads_moderated' ,
'title' => '_MI_ADS_MODERAT' ,
'description' => '',
'formtype' => 'yesno' ,
'valuetype' => 'int' ,
'default' => '0' ,
'options' => [],
];

// $xoopsModuleConfig['perpage']
$modversion['config'][] = [
'name' => 'ads_perpage' ,
'title' => '_MI_ADS_PERPAGE' ,
'description' => '',
'formtype' => 'select' ,
'valuetype' => 'int' ,
'default' => '10' ,
'options' => ['10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '35' => 35, '40' => 40, '50' => 50],
];

// $xoopsModuleConfig['newad']
$modversion['config'][] = [
'name' => 'ads_newad' ,
'title' => '_MI_ADS_VIEWNEWCLASS' ,
'description' => '_MI_ADS_ONHOME',
'formtype' => 'yesno' ,
'valuetype' => 'int' ,
'default' => '1' ,
'options' => [],
];

// $xoopsModuleConfig['newclassifieds']
$modversion['config'][] = [
'name' => 'newclassified_ads' ,
'title' => '_MI_ADS_NUMNEW' ,
'description' => '_MI_ADS_ONHOME',
//	'formtype' => 'select' ,

'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '10' ,
//	'options' => array('5'=>5, '10'=>10, '15'=>15, '20'=>20, '25'=>25, '30'=>30, '35'=>35, '40'=>40, '50'=>50)

'options' => [],
];

// $xoopsModuleConfig['countday']
$modversion['config'][] = [
'name' => 'ads_countday' ,
'title' => '_MI_ADS_NEWTIME' ,
'description' => '_MI_ADS_INDAYS',
//	'formtype' => 'select' ,

'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '3' ,
//	'options' => array('1'=>1, '2'=>2, '3'=>3, '4'=>4, '5'=>5, '6'=>6, '7'=>7, '8'=>8, '9'=>9, '10'=>10, '20'=>20, '30'=>30, '40'=>40, '50'=>50)

'options' => [],
];

$modversion['config'][] = [
'name' => 'ads_login_ok' ,
'title' => '_MI_ADS_MUSTLOGIN' ,
'description' => '_MI_ADS_THRUMAIL',
'formtype' => 'yesno' ,
'valuetype' => 'int' ,
'default' => '0' ,
'options' => [],
];

// $xoopsModuleConfig['photomax']
$modversion['config'][] = [
'name' => 'ads_photomax' ,
'title' => '_MI_ADS_MAXIIMGS' ,
'description' => '_MI_ADS_INBYTES',
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '30000' ,
'options' => [],
];

// $xoopsModuleConfig['maxwide']
$modversion['config'][] = [
'name' => 'ads_maxwide' ,
'title' => '_MI_ADS_MAXWIDE' ,
'description' => '_MI_ADS_INPIXEL',
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '500' ,
'options' => [],
];

// $xoopsModuleConfig['maxhigh']
$modversion['config'][] = [
'name' => 'ads_maxhigh' ,
'title' => '_MI_ADS_MAXHIGH' ,
'description' => '_MI_ADS_INPIXEL',
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '400' ,
'options' => [],
];

// $xoopsModuleConfig['adsdays']
$modversion['config'][] = [
'name' => 'ads_howlong' ,
'title' => '_MI_ADS_DAYS' ,
'description' => '_MI_ADS_INDAYS',
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '14' ,
'options' => [],
];

// $xoopsModuleConfig['affichebloc']
$modversion['config'][] = [
'name' => 'ads_affichebloc' ,
'title' => '_MI_ADS_TYPEBLOC' ,
'description' => '',
'formtype' => 'select' ,
'valuetype' => 'text' ,
'default' => '1' ,
'options' => ['_MI_ADS_LASTTEN' => '1', '_MI_ADS_JOBRAND' => '2'],
];

// $xoopsModuleConfig['souscat']
$modversion['config'][] = [
'name' => 'ads_souscat',
'title' => '_MI_ADS_DISPLSUBCAT',
'description' => '_MI_ADS_ONHOME',
'formtype' => 'yesno',
'valuetype' => 'int',
'default' => '1',
'options' => [],
];

// $xoopsModuleConfig['nbsouscat']
$modversion['config'][] = [
'name' => 'ads_nbsouscat',
'title' => '_MI_ADS_NBDISPLSUBCAT',
'description' => '',
'formtype' => 'textbox',
'valuetype' => 'int',
'default' => '4',
'options' => [],
];

// $xoopsModuleConfig['classm']
$modversion['config'][] = [
'name' => 'ads_classm',
'title' => '_MI_ADS_ORDRECLASS',
'description' => '',
'formtype' => 'select',
'valuetype' => 'text',
'default' => 'title',
'options' => ['_MI_ADS_ORDREALPHA' => 'title', '_MI_ADS_ORDREPERSO' => 'ordre' ],
];

// $xoopsModuleConfig['ads_rate_user']
$modversion['config'][] = [
'name' => 'ads_rate_user',
'title' => '_MI_ADS_RATE_USER',
'description' => '',
'formtype' => 'yesno',
'valuetype' => 'int',
'default' => '0',
'options' => [],
];

// $xoopsModuleConfig['ads_rate_item']
$modversion['config'][] = [
'name' => 'ads_rate_item',
'title' => '_MI_ADS_RATE_ITEM',
'description' => '',
'formtype' => 'yesno',
'valuetype' => 'int',
'default' => '0',
'options' => [],
];

//Notification
$modversion['hasNotification'] = 1;

$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'ads_notify_iteminfo';

//category
$modversion['notification']['category'][1]['name'] = 'category';
$modversion['notification']['category'][1]['title'] = _MI_ADS_CATEGORY_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_ADS_CATEGORY_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][1]['item_name'] = 'cid';
$modversion['notification']['category'][1]['allow_bookmark'] = 0;
$modversion['notification']['category'][1]['extraParams'] = ['pa'];

$modversion['notification']['category'][2]['name'] = 'listing';
$modversion['notification']['category'][2]['title'] = _MI_ADS_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_ADS_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][2]['item_name'] = 'lid';
$modversion['notification']['category'][2]['allow_bookmark'] = 0;
$modversion['notification']['category'][2]['extraParams'] = ['pa'];

$modversion['notification']['category'][3]['name'] = 'global';
$modversion['notification']['category'][3]['title'] = _MI_ADS_GLOBAL_NOTIFY;
$modversion['notification']['category'][3]['description'] = _MI_ADS_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][3]['extraParams'] = ['pa'];

//event
//jobs notifications new listings in this category
$modversion['notification']['event'][1]['name'] = 'new_listing';
$modversion['notification']['event'][1]['category'] = 'category';
$modversion['notification']['event'][1]['title'] = _MI_ADS_NEWPOST_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_ADS_NEWPOST_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_ADS_NEWPOST_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'listing_newpost_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_ADS_NEWPOST_NOTIFYSBJ;

//new listings in all categories posted
$modversion['notification']['event'][2]['name'] = 'new_listing';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['title'] = _MI_ADS_GLOBAL_NEWPOST_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_ADS_GLOBAL_NEWPOST_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_ADS_GLOBAL_NEWPOST_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'listing_newpost_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_ADS_GLOBAL_NEWPOST_NOTIFYSBJ;
